### ISSUE TITLE
Invalid input: date_trans works with objects of class Date only

### ISSUE THREAD

**Issue by bajun65537** [dplloyd/edinburgh_bike_hire#1]
Hello! When trying to implement the code I encountered an error. For the heatmap, e.g. when defining `cycle_tiles` I get the following message: `Invalid input: date_trans works with objects of class Date only`.  Actually, I can define the `cycle_tiles` but when I try to call it unfortunately I get that error. A similar error occurs for any other part making it impossible to create a heatmap. Could you try to reproduce that error and if so, how does one go about it?

**Comment by dplloyd** [comment]
Hi! Yes, I was able to reproduce the error. I hoped it was a version issue at first, but actually, I think I may have introduced it last month. It seems `trip_week` wasn't in date format - not sure how I managed to remove that step from a previous version. Let me know how you get on with the updated version!

**Comment by bajun65537** [comment]
Everything's fine and dandy now. Thanks!
